export const areaOptions = [
    {
        label: '서울',
        value: 'I000',
        children: [
            { label: '강남구', value: 'I010' },
            { label: '강동구', value: 'I020' },
            { label: '강북구', value: 'I030' },
            { label: '강서구', value: 'I040' },
            { label: '관악구', value: 'I050' },
            { label: '광진구', value: 'I060' },
            { label: '구로구', value: 'I070' },
            { label: '금천구', value: 'I080' },
            { label: '노원구', value: 'I090' },
            { label: '도봉구', value: 'I100' },
            { label: '동대문구', value: 'I110' },
            { label: '동작구', value: 'I120' },
            { label: '마포구', value: 'I130' },
            { label: '서대문구', value: 'I140' },
            { label: '서초구', value: 'I150' },
            { label: '성동구', value: 'I160' },
            { label: '성북구', value: 'I170' },
            { label: '송파구', value: 'I180' },
            { label: '양천구', value: 'I190' },
            { label: '영등포구', value: 'I200' },
            { label: '용산구', value: 'I210' },
            { label: '은평구', value: 'I220' },
            { label: '종로구', value: 'I230' },
            { label: '중구', value: 'I240' },
            { label: '중랑구', value: 'I250' },
        ],
        },
        {
        label: '경기',
        value: 'B000',
        children: [
            { label: '가평군', value: 'B010' },
            { label: '고양시 덕양구', value: 'B020' },
            { label: '고양시 일산동구', value: 'B030' },
            { label: '고양시 일산서구', value: 'B031' },
            { label: '과천시', value: 'B040' },
            { label: '광명시', value: 'B050' },
            { label: '광주시', value: 'B060' },
            { label: '구리시', value: 'B070' },
            { label: '군포시', value: 'B080' },
            { label: '김포시', value: 'B090' },
            { label: '남양주시', value: 'B100' },
            { label: '동두천시', value: 'B110' },
            { label: '부천시', value: 'B125' },
            { label: '성남시 분당구', value: 'B150' },
            { label: '성남시 수정구', value: 'B160' },
            { label: '성남시 중원구', value: 'B170' },
            { label: '수원시 권선구', value: 'B180' },
            { label: '수원시 장안구', value: 'B190' },
            { label: '수원시 팔달구', value: 'B200' },
            { label: '수원시 영통구', value: 'B201' },
            { label: '시흥시', value: 'B210' },
            { label: '안산시 단원구', value: 'B220' },
            { label: '안산시 상록구', value: 'B221' },
            { label: '안성시', value: 'B230' },
            { label: '안양시 동안구', value: 'B240' },
            { label: '안양시 만안구', value: 'B250' },
            { label: '양주시', value: 'B260' },
            { label: '양평군', value: 'B270' },
            { label: '여주시', value: 'B280' },
            { label: '연천군', value: 'B290' },
            { label: '오산시', value: 'B300' },
            { label: '용인시 기흥구', value: 'B310' },
            { label: '용인시 수지구', value: 'B311' },
            { label: '용인시 처인구', value: 'B312' },
            { label: '의왕시', value: 'B320' },
            { label: '의정부시', value: 'B330' },
            { label: '이천시', value: 'B340' },
            { label: '파주시', value: 'B350' },
            { label: '평택시', value: 'B360' },
            { label: '포천시', value: 'B370' },
            { label: '하남시', value: 'B380' },
            { label: '화성시', value: 'B390' },
        ],
        },
        {
        label: '인천',
        value: 'K000',
        children: [
            { label: '강화군', value: 'K010' },
            { label: '계양구', value: 'K020' },
            { label: '미추홀구', value: 'K030' },
            { label: '남동구', value: 'K040' },
            { label: '동구', value: 'K050' },
            { label: '부평구', value: 'K060' },
            { label: '서구', value: 'K070' },
            { label: '연수구', value: 'K080' },
            { label: '옹진군', value: 'K090' },
            { label: '중구', value: 'K100' },
        ],
        },
        {
        label: '강원',
        value: 'A000',
        children: [
            { label: '강릉시', value: 'A010' },
            { label: '고성군', value: 'A020' },
            { label: '동해시', value: 'A030' },
            { label: '삼척시', value: 'A040' },
            { label: '속초시', value: 'A050' },
            { label: '양구군', value: 'A060' },
            { label: '양양군', value: 'A070' },
            { label: '영월군', value: 'A080' },
            { label: '원주시', value: 'A090' },
            { label: '인제군', value: 'A100' },
            { label: '정선군', value: 'A110' },
            { label: '철원군', value: 'A120' },
            { label: '춘천시', value: 'A130' },
            { label: '태백시', value: 'A140' },
            { label: '평창군', value: 'A150' },
            { label: '홍천군', value: 'A160' },
            { label: '화천군', value: 'A170' },
            { label: '횡성군', value: 'A180' },
        ],
        },
        {
        label: '대전',
        value: 'G000',
        children: [
            { label: '대덕구', value: 'G010' },
            { label: '동구', value: 'G020' },
            { label: '서구', value: 'G030' },
            { label: '유성구', value: 'G040' },
            { label: '중구', value: 'G050' },
        ],
        },
    {
        label: '세종',
        value: '1000',
        children: [
            { label: '세종시', value: '1010' },
        ],
    },
    {
        label: '충남',
        value: 'O000',
        children: [
            { label: '계룡시', value: 'O160' },
            { label: '공주시', value: 'O010' },
            { label: '금산군', value: 'O020' },
            { label: '논산시', value: 'O030' },
            { label: '당진시', value: 'O040' },
            { label: '보령시', value: 'O050' },
            { label: '부여군', value: 'O060' },
            { label: '서산시', value: 'O070' },
            { label: '서천군', value: 'O080' },
            { label: '아산시', value: 'O090' },
            { label: '예산군', value: 'O110' },
            { label: '천안시 동남구', value: 'O120' },
            { label: '천안시 서북구', value: 'O121' },
            { label: '청양군', value: 'O130' },
            { label: '태안군', value: 'O140' },
            { label: '홍성군', value: 'O150' },
        ],
    },
    {
        label: '충북',
        value: 'P000',
        children: [
            { label: '괴산군', value: 'P010' },
            { label: '단양군', value: 'P020' },
            { label: '보은군', value: 'P030' },
            { label: '영동군', value: 'P040' },
            { label: '옥천군', value: 'P050' },
            { label: '음성군', value: 'P060' },
            { label: '제천시', value: 'P070' },
            { label: '증평군', value: 'P130' },
            { label: '진천군', value: 'P080' },
            { label: '청주시 상당구', value: 'P100' },
            { label: '청주시 서원구', value: 'P140' },
            { label: '청주시 청원구', value: 'P090' },
            { label: '청주시 흥덕구', value: 'P110' },
            { label: '충주시', value: 'P120' },
        ],
    },
    {
        label: '부산',
        value: 'H000',
        children: [
            { label: '강서구', value: 'H010' },
            { label: '금정구', value: 'H020' },
            { label: '기장군', value: 'H030' },
            { label: '남구', value: 'H040' },
            { label: '동구', value: 'H050' },
            { label: '동래구', value: 'H060' },
            { label: '부산진구', value: 'H070' },
            { label: '북구', value: 'H080' },
            { label: '사상구', value: 'H090' },
            { label: '사하구', value: 'H100' },
            { label: '서구', value: 'H110' },
            { label: '수영구', value: 'H120' },
            { label: '연제구', value: 'H130' },
            { label: '영도구', value: 'H140' },
            { label: '중구', value: 'H150' },
            { label: '해운대구', value: 'H160' },
        ],
    },
    {
        label: '울산',
        value: 'J000',
        children: [
            { label: '남구', value: 'J010' },
            { label: '동구', value: 'J020' },
            { label: '북구', value: 'J030' },
            { label: '울주군', value: 'J040' },
            { label: '중구', value: 'J050' },
        ],
    },
    {
        label: '경남',
        value: 'C000',
        children: [
            { label: '거제시', value: 'C010' },
            { label: '거창군', value: 'C020' },
            { label: '고성군', value: 'C030' },
            { label: '김해시', value: 'C040' },
            { label: '남해군', value: 'C050' },
            { label: '밀양시', value: 'C080' },
            { label: '사천시', value: 'C090' },
            { label: '산청군', value: 'C100' },
            { label: '양산시', value: 'C110' },
            { label: '의령군', value: 'C120' },
            { label: '진주시', value: 'C130' },
            { label: '창녕군', value: 'C150' },
            { label: '창원시 마산합포구', value: 'C160' },
            { label: '창원시 마산회원구', value: 'C162' },
            { label: '창원시 성산구', value: 'C164' },
            { label: '창원시 의창구', value: 'C166' },
            { label: '창원시 진해구', value: 'C168' },
            { label: '통영시', value: 'C170' },
            { label: '하동군', value: 'C180' },
            { label: '함안군', value: 'C190' },
            { label: '함양군', value: 'C200' },
            { label: '합천군', value: 'C210' },
        ],
    },
    {
        label: '경북',
        value: 'D000',
        children: [
            { label: '경산시', value: 'D010' },
            { label: '경주시', value: 'D020' },
            { label: '고령군', value: 'D030' },
            { label: '구미시', value: 'D040' },
            { label: '김천시', value: 'D060' },
            { label: '문경시', value: 'D070' },
            { label: '봉화군', value: 'D080' },
            { label: '상주시', value: 'D090' },
            { label: '성주군', value: 'D100' },
            { label: '안동시', value: 'D110' },
            { label: '영덕군', value: 'D120' },
            { label: '영양군', value: 'D130' },
            { label: '영주시', value: 'D140' },
            { label: '영천시', value: 'D150' },
            { label: '예천군', value: 'D160' },
            { label: '울릉군', value: 'D170' },
            { label: '울진군', value: 'D180' },
            { label: '의성군', value: 'D190' },
            { label: '청도군', value: 'D200' },
            { label: '청송군', value: 'D210' },
            { label: '칠곡군', value: 'D220' },
            { label: '포항시 남구', value: 'D230' },
            { label: '포항시 북구', value: 'D240' },
        ],
    },
    {
        label: '대구',
        value: 'F000',
        children: [
            { label: '군위군', value: 'F090' },
            { label: '남구', value: 'F010' },
            { label: '달서구', value: 'F020' },
            { label: '달성군', value: 'F030' },
            { label: '동구', value: 'F040' },
            { label: '북구', value: 'F050' },
            { label: '서구', value: 'F060' },
            { label: '수성구', value: 'F070' },
            { label: '중구', value: 'F080' },
        ],
    },
    {
        label: '광주',
        value: 'E000',
        children: [
            { label: '광산구', value: 'E010' },
            { label: '남구', value: 'E020' },
            { label: '동구', value: 'E030' },
            { label: '북구', value: 'E040' },
            { label: '서구', value: 'E050' },
        ],
    },
    {
        label: '전남',
        value: 'L000',
        children: [
            { label: '강진군', value: 'L010' },
            { label: '고흥군', value: 'L020' },
            { label: '곡성군', value: 'L030' },
            { label: '광양시', value: 'L040' },
            { label: '구례군', value: 'L050' },
            { label: '나주시', value: 'L060' },
            { label: '담양군', value: 'L070' },
            { label: '목포시', value: 'L080' },
            { label: '무안군', value: 'L090' },
            { label: '보성군', value: 'L100' },
            { label: '순천시', value: 'L110' },
            { label: '신안군', value: 'L120' },
            { label: '여수시', value: 'L130' },
            { label: '영광군', value: 'L140' },
            { label: '영암군', value: 'L150' },
            { label: '완도군', value: 'L160' },
            { label: '장성군', value: 'L170' },
            { label: '장흥군', value: 'L180' },
            { label: '진도군', value: 'L190' },
            { label: '함평군', value: 'L200' },
            { label: '해남군', value: 'L210' },
            { label: '화순군', value: 'L220' },
        ],
    },
    {
        label: '전북',
        value: 'M000',
        children: [
            { label: '고창군', value: 'M010' },
            { label: '군산시', value: 'M020' },
            { label: '김제시', value: 'M030' },
            { label: '남원시', value: 'M040' },
            { label: '무주군', value: 'M050' },
            { label: '부안군', value: 'M060' },
            { label: '순창군', value: 'M070' },
            { label: '완주군', value: 'M080' },
            { label: '익산시', value: 'M090' },
            { label: '임실군', value: 'M100' },
            { label: '장수군', value: 'M110' },
            { label: '전주시 덕진구', value: 'M120' },
            { label: '전주시 완산구', value: 'M130' },
            { label: '정읍시', value: 'M140' },
            { label: '진안군', value: 'M150' },
        ],
    },
    {
        label: '제주',
        value: 'N000',
        children: [
            { label: '서귀포시', value: 'N030' },
            { label: '제주시', value: 'N040' },
        ],
    },
];